language: python

env:
  global:
    - secure: mEkqlpcfUvShRE7dj2bxpFzvHjDoIjcvHduA4JX4gZfVVwDeEgFC9Pbb0oaR7xEiKeKSQ7IT0FyD6hteNviGSSebg6xkqWmhxSzI4fVk/hJ8FZVRsdNr6zEDhl1PNdmZL+UGauKGh5STbHXgSv1J/TOKwqzPBC7CpHXdRjPn1DfA7r9dkh1yWI1ONA+iFbkY7DhWer+9FgwET/StIbmYE0+eb+1lHQ7FSTnVAfTZl2eljaTly4VVqNPgyfbjc1//ieomrB6c+ziEyW6SeizQZrNeX6s90TKIN35rtE44WO4IH8y4bGEmsn5dQBf4g/m5je0rIvJG9Ag+WUwpGuOCKuHVBTI8hPpepaQyaQ4L2VZbu06rnt5AwqjnHDrXfxnPbctBKyiqtN47STTiLz6jdVhPEAebz7LMIKXKPC3lS7u0BOPq2pIDf7UruWLdYWsxWkR8MSY8JPrq6IezyJbrN9vIQtdKMm4UrTIfhUEyGYbTPSZooc/KqP2p/EfbwjePBtg1kSVoajvHtMItTrcQPM4kVxg5kp8HQvwEK4ts9/2Ew0/rwE1P63ozU2hFd1cuMalz43bq52vy4rfnfOlPZok0dzTfB0GGCU0OAYZ4H9nQ2mMD4t4fKZoPFBD+eIlYih4BX8C+rqbg8WMqkhVNV630JbR0Fj4cUmEW6XpbRJI=
    - secure: NeH/++qkbE7xvxJXY0C/Rjl8VNgtCuxiZSV3yEoFBoZY0Hp/LgA/rO8ZhGdY09u17Gzfazw4P0RbFO0kkwCaNAM5WMIt0hFN2kWHzXxy97ahtrR/8yqF2Jib6104Y+rkraWDyP0n9KJc1t5Wsk8zdvxXOaETgkTNFsDVF3fKNuuV6URUwbKHqJQPAEj+J45AcR54F4A/NvS1ehUJrha4Ap28FR41rXPxiQ590clfB/AYQeSV+XqY+Svo8nE5e0iZTQ6kW/kKRs41mn1FzXe+5jxen0ZIh/8HtGT1F+QKBOw2Rqj8oI+NReNH6SMPINYE7EgDB6R4g6css4r7tfY2GeVCpJhV7TpDROS2Ygw+c88SebD191AgoE7qVuW7zQ1FsZKXkkx02M7laPAGaXlK7tCiXBE+EG66/4rlnXcWF94995w6HGvP9CBanIRGi7Yt9jcY4XdIV8T979EunII4ZcrIPOgCmUfCO8dbRJI3Ct2V7eerXc31qPzTrGzP2ADcjwSYifzyHaTNvcxnBneSj248l5I2GqrazlrEhpQx0G+p0gBRPTtzBo5DTCKkJ3sv+BpzIi/rSILBPBsaVdx/M6a7w1wKHyFDHqRykpRfxrl0dLWTOLoYGcxQ+sIqgRGQI1pHZICWrOuT2VmnXJ2Z8idPSkjHGH6bsrfppBDh/b0=


matrix:
  include:
    - python: '2.7'
      env:
        - SO_DISABLE_MOCKS: "1"
        - SO_S3_URL: "s3://affectiva-travis-smart-open-test/py27"
        - SO_S3_RESULT_URL: "s3://affectiva-travis-smart-open-test/py27-results"

    - python: '3.5'

    - python: '3.6'
      env:
        - SO_DISABLE_MOCKS: "1"
        - SO_S3_URL: "s3://affectiva-travis-smart-open-test/py36"
        - SO_S3_RESULT_URL: "s3://affectiva-travis-smart-open-test/py36-results"

    - python: '3.7'
      env:
        - SO_DISABLE_MOCKS: "1"
        - SO_S3_URL: "s3://affectiva-travis-smart-open-test/py37"
        - SO_S3_RESULT_URL: "s3://affectiva-travis-smart-open-test/py37-results"
        - BOTO_CONFIG: "/dev/null"
      dist: xenial


install:
  - pip install --upgrade setuptools
  - pip install .[test]
  - pip freeze


script:
  - if [[ ${TRAVIS_SECURE_ENV_VARS} = false ]]; then
      echo "DISABLE INTEGRATION TESTING FOR S3";
      unset SO_DISABLE_MOCKS;
      unset SO_S3_URL;
      unset SO_S3_RESULT_URL;
    fi
  - python setup.py test
  - export SO_S3_URL=$SO_S3_URL/$(python -c 'from uuid import uuid4;print(uuid4())')
  - pip install pytest
  - py.test integration-tests/test_http.py
  - if [[ ${SO_DISABLE_MOCKS} = "1" ]]; then
      pip install pytest_benchmark awscli;
      set -e;
      py.test integration-tests/test_s3.py --benchmark-save=`git rev-parse HEAD`;
      set +e;
      aws s3 cp .benchmarks/*/*.json ${SO_S3_RESULT_URL};
      aws s3 rm --recursive $SO_S3_URL;
    fi
  - pip install numpy
  - py.test integration-tests/test_207.py


cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"
